### PR TITLE
HPA for gateway and loki-multi-tenant-proxy

### PR DESCRIPTION
**Pull request by hervenicol**
Towards https://github.com/giantswarm/roadmap/issues/2365
- add HPA for multi-tenant-proxy
- enable HPA for gateway by default

### CODE REVIEW

**Comment by hervenicol** [comment]
Remarks:
- the "Align" commit is common with `master`. Why does it appear in my PR, as it's already part of `master`?
- tested on a WC on `gauss`, upgrade from 0.8.0 looks good.

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Have you tried to rebase the master branch?

**Comment by hervenicol** [comment]
> Have you tried to rebase the master branch?

Yes, that's the reason I have this commit in my branch.

**Comment by QuentinBisson** [comment]
Is your master branch in Sync with thé origin/master? It does feel a bit weird

**Comment by hervenicol** [comment]
> Is your master branch in Sync with thé origin/master? It does feel a bit weird

AFAIK, yes.

Maybe I forgot something essential in my git-fu?

```
[loki-app]$ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
[loki-app]$ git pull
Already up to date.
[loki-app]$ git checkout adjust_resources 
Switched to branch 'adjust_resources'
Your branch is up to date with 'origin/adjust_resources'.
[loki-app]$ git rebase master 
Successfully rebased and updated refs/heads/adjust_resources.
[loki-app]$ git push
Everything up-to-date
[loki-app]$ 
```

**Comment by QuentinBisson** [comment]
I usually use rebase -i but your commands look alright to me 😅

**Review by QuantumEnigmaa — APPROVED** [review]

**Review by QuentinBisson — APPROVED** [review]
LGTM

**Pull request merged**
