### PR TITLE
improve upgrade path

### PR DESCRIPTION
**Pull request by hervenicol**
Towards https://github.com/giantswarm/giantswarm/issues/24640

Improve upgrade documentation for customers.
Once we are happy with it we can push this release to  GA.

Links are broken in `README` because I set the (expected) address after merge.
Has to be an absolute URL to work from Happa.

Note to reviewers: please also read the `UPGRADE` guide, and tell me if anything is missing.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
I really like it. I'd like if we have the same structure everywhere though. Let's open an issue once we are done with this one :)

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuantumEnigmaa** [comment]
LGTM, pretty straight forward

**Review by QuantumEnigmaa — APPROVED** [review]

**Review by TheoBrigitte — COMMENTED** [review]
Here are few remarks on the UPGRADE guide https://github.com/giantswarm/loki-app/blob/release-v0.5.x/UPGRADE.md

* `Basic upgrade procedure > 3 prepare your new values file` this does not explain much, what should I prepare ? I think we should mention the new structure and link to an example. Ideally we have an example on how it was before and how it looks like now
* ` Notes > Your values.yaml file need some adjustments. > See example values files` please add a link to the values example file you are talking about
* Replace `gauss` with a generic name like `tenant1`, and maybe add another `tenant2` to align with `tenant1|tenant2` you speak about just before

**Comment by hervenicol** [comment]
@TheoBrigitte , latest commit should include your suggestions. WDYT?

**Pull request merged**
