### PR TITLE
add CNPs for write and backend pods

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
Towards https://github.com/giantswarm/roadmap/issues/3189

These CNPs could otherwise be added as extra-objects in the config. Or we could create an "additionalCiliumNetPols" field upstream (or something of the sort). 
Until we decide on any of those, this will allow loki to work on CAPVCD clusters

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
LGTM if tested also on vintage :)

**Comment by QuentinBisson** [comment]
Sure :) then make sure to also do the config change

**Comment by marieroque** [comment]
No more error on `golem`, it was related to https://github.com/giantswarm/loki-app/blob/master/CHANGELOG.md#fixed
We had to delete the loki-multi-tenant-proxy deployment.

**Review by marieroque — APPROVED** [review]
LGTM

**Pull request merged**
