### PR TITLE
add monitoring labels

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR adds the giantswarm scraping labels to loki services.

@giantswarm/team-atlas can you take a look and tell me if this is the right way to do this?

### CODE REVIEW

**Comment by ubergesundheit** [comment]
need to address https://github.com/giantswarm/giantswarm/issues/17947

**Review by webwurst — APPROVED** [review]

**Review by ced0ps — COMMENTED** [review]
Wouldn't it be more convenient to make all these changes in the _helpers.tpl? Then you'd only have to change one file?

**Comment by mig4** [comment]
Yeah, there's a lot of services and deployments here so it would probably make sense to move the definitions into `_helpers.tpl` and re-use them. Other than that seems OK to me.

**Comment by ubergesundheit** [comment]
> Wouldn't it be more convenient to make all these changes in the _helpers.tpl? Then you'd only have to change one file?

I checked again and while you're right, I think this is still the right way to do this.

Adding this to the main labels template would add this label to all kinds of resources and also to components where I don't want this label to appear (memcached for example). And the global label helper is used not only deployments and services, but also pvcs, service accounts etc. I think this is not desired.

For each component there is actually an own helper for labels, but again the helper is used for all kinds of resources.

Finally we also need the annotation. Ok I could add a new helper for annotations, but for a single annotation seems unnecessary to me.

WDYT?

**Comment by mig4** [comment]
Sure, I meant creating new "variables" in helpers instead of adding to existing ones, just so that if the value ever changes, you can just update one place. But then I guess these don't really change that often and search&replace works too.

And yeah I also wasn't sure if there's that much repetition given that some resources have some labels, others have a label and annotation, etc. so it might just be too much effort compared to the benefit as you say.

**Review by mig4 — APPROVED** [review]

**Comment by ubergesundheit** [comment]
In fact, we we're discussing a mechanism to allow enabling/disabling monitoring/scraping labels through a switch in the apps values. Then we would require a helper. 

I think I'll spend some time to check again how feasible this would be. Thanks for you input :+1:

**Comment by ubergesundheit** [comment]
Quick update before I finally merge:

I've moved the `giantswarm.io/service-type: "managed"` into the main labels helper, the others are too specific to either Serivices or Deployments. I don't want them to end up somewhere I dont want them to end up. (For example PVC, NetworkPolicies, etc)

**Pull request merged**
